# cloud-config
resize_rootfs: true

write_files:
- content: |
    vm_name=${vm_name}
    vm_names="${vm_names}"
    vm_ip=${vm_ip}
    vm_ips=${vm_ips}
    vm_ip_network=${vm_ip_network}
    vm_swap_size="${vm_swap_size}"
    vm_reg_code="${vm_reg_code}"
    vm_reg_email="${vm_reg_email}"
    vm_number="${vm_number}"
    sap_media_local="${sap_media_local}"
    sap_media_storage="${sap_media_storage}"
    sap_media_key="${sap_media_key}"
    sap_media_add_fstab="${sap_media_add_fstab}"
    admin_password=${admin_password}
    storage_account="${storage_account}"
    lb_private_ip="${lb_private_ip}"
    enable_monitoring=${enable_monitoring}
    cluster_unicast=${cluster_unicast}
    cluster_password=${cluster_password}
    subscription_id=${subscription_id}
    resource_group=${resource_group}
    tenant_id=${tenant_id}
    login_id=${login_id}
    app_password=${app_password}
    sap_ascs_instance_sid=${sap_ascs_instance_sid}
    sap_ascs_instance_id=${sap_ascs_instance_id}
    sap_ascs_root_user=${sap_ascs_root_user}
    sap_ascs_root_password=${sap_ascs_root_password}
    sap_ascs_vip_address=${sap_ascs_vip_address}
    sap_ascs_vip_hostname=${sap_ascs_vip_hostname}
    sap_ers_instance_sid=${sap_ers_instance_sid}
    sap_ers_instance_id=${sap_ers_instance_id}
    sap_ers_root_user=${sap_ers_root_user}
    sap_ers_root_password=${sap_ers_root_password}
    sap_ers_vip_address=${sap_ers_vip_address}
    sap_ers_vip_hostname=${sap_ers_vip_hostname}
    sid_adm_password=${sid_adm_password}
    sap_adm_password=${sap_adm_password}
    master_password=${master_password}
    sapmnt_path=${sapmnt_path}
    sidadm_user_uid=${sidadm_user_uid}
    sidadm_user_gid=${sidadm_user_gid}
    sapmnt_inst_media=${sapmnt_inst_media}
    swpm_folder=${swpm_folder}
    sapexe_folder=${sapexe_folder}
    additional_dvds=${additional_dvds}
    sap_hana_host=${sap_hana_host}
    sap_hana_ip=${sap_hana_ip}
    sap_hana_sid=${sap_hana_sid}
    sap_hana_instance=${sap_hana_instance}
    sap_hana_password=${sap_hana_password}
  path: /run/scripts/vars
  owner: root:root
  permissions: "0640"
  append: false
- encoding: gzip+base64
  content: |
    H4sICNU/i2ACA3NldHVwX2FzY3Muc2gA7T3bdttGks/Dr+iRnKEUCwBJSXbMGeZEsZWJd2NHKzrJzokT
    HBBoiohwCxogxTjMv+zZh/2Q+bGtqr7gQlByYjubzcQnxya6q6urq+veDWT/z84sTJyZJxa93j77LPUC
    VvA89+ZpHrOll4veahFGnH3N/sysOXPyMnGEn4dZIRzsZt/8lQUpExHnGRvi74T3RFrmPt8GximmvCgz
    JlZexkoRJlfs7Icy5yzgyxCGzKLUv+4JHjArZHvCueQS15NQXNvniTeL+BSGTpKdPWtnjzm88J2V513x
    pLD9NJnvwogjpuEP/NnHk8HOnnuvlrGLBLsCGjbd+Nei4LFfRCznovDyguluwXNcWY/B2i/5VQhwOZPg
    LEzY9PHj3vSL6fnjNEm4XzArZzRfzq9cPw34hlm8auGxF0abHqGaw0wLmC5LRe+HdZYB2pzPsU9ygyFa
    FqdBGXHRnCPD/bJkl5WVsyj0LT9Ky8AZntoj5+aDB+6DE8T0RRZ4BVfk6lmshMEOWhECPE1gtVEk58o8
    /xoWLRgID5ueXbCzLAPUXhGmSW0wrNoqALgATiRMIF+BR8gVL7OSFVt4rkCSGyMW3ixNC1HkAIOyWUYe
    wier7eaXPQZdUWHFYQIzM5ECCbgvtLsWbQvQyJPqAYdk62KRJseWh/JoxVdxYflpnJWw/mZXGMCYsFir
    iTJLlIID/0rcWhhDTAYOwAp90qpnaZkU7NOz52fsGQ9Cr0fKFMC24uJjbHJB7r1ow75hf/kLi6+DMMdd
    2gbQQ/dIBEU883NO5HiR2GuN7gDpqcc5qPSkC4cDUwLtwBbX832ke2Nj914Pefi3v51//gn7EOmq8Gx6
    sPw88WI+2R7cyzwhVmkeTOpruebrTQ9Q9Xr+AqSQPRgM2jjDOZic+hgvCNw5CNtswyasyEuOlqdY8AQ2
    gfuLFFjSRTxiAxXNub0KkyBdCTvhRR2vGrFhXdvB/HAuGEvSOejdEciomBzbg6MawyZNuo+A9y4siU8G
    Dx8+PMK22qOU8zBJ99iHH8r9oSXBEmKSkY4N55Hgph/0hih6w6V2rNRK2dtbXm8egty/+PzJ52N29l2J
    BpF96eXhP/9ryUPBOAMlAUi0hGjwUwG6knvgDwAOaPayDLRGyrEDlMZJUT2XIsc2bNAsSYAjhn42HNgD
    e2g/GKPLUcPraF5zVH0mcIVWPtdInPdrTQoI2z4Jb+Q6QjKK3j//55//nbJ5mfhghbzcLMGqcDufng2d
    6T+mDr/hO/vPL6fDAUGgooEeoNHxghhNC1rYtbQ0rEgZGSiXTJudrXtSLwgGPe0OMBaFs9zL18y27aae
    O0WcOU1gW1o1y7JaWP40GoyG1mBkjR6w4aPxaDg+HdoD/Yfdx7979+/fbw0DGV2poSfWcMhGx+Phw/Hp
    I/v05Pjh8ejkgxM19KOPmDV6NDoaPmL31b8ffQSKof7M8zRmsSDvixPYchrPL8Ild4GtZJPXLIyzFLzz
    s+nTsxKtR6H9k8FUk36wNFuAB4cSlEdgoshpujxZhnmaxAA07lkNiiQt4EfiNLHrmBUdUxkdXIDW+GHm
    RY9rttrqpuiWIQe9+x2zG3+l5nwchdAw5YC2qAZXQ5vTdUMfVPyiIQTkhgEMwHgovLJrvv9pcFQtBv8I
    wtYJ++983QIueOIlNeAX9BwCzvsdJNyF+v426gbZFfbWAlsbPdlqqQYYCRH8D3n41eThnYpDY3PlA+At
    IX6tR1cY0pRJeDMKwKXtNp7SDlsWZF5odqWxX3g5dwiwNegWRD1ICzDwEpMDShHo9+YQm8NMN8IvaNpn
    j2lFmGthcGxi9IBnUbomAa6ZfhkaApwjg2g7QHckcx3y+jmG3WPgBKSOfEwcscBB5ksapZ+rlVFAriJ0
    4YCRLrjkl45oaWwWRhHEAK04tuppkFg1O0Wa2QI2QBPTf7+vaVJxuXqC6GLFPfD5KvysO7saPjWIcKrf
    iA+YKB8Ychoa8J8x5CbVJMCtYsyq3fh68M0Gmle4X0F6JamSmdcYMpN5AY3UJhPgMXPgh6PBCSEgnnvY
    xYvFAFpAwnxP0CxqXlc14UwQGIQJbDp2RzM3y8Ml8BoaNhRFAnkpWApIJSlJDBBM/nSrTgSFQDIV68SX
    FBcpJIBjpQVFes2TMTsmvyybKiqNpoB0BxjMBUGuGBJmLvI/za83BPV9mealwcpvMvDRPHCXMJfQPCzj
    Gc8R3DDZ1SnFmO1VHNCNmz1MysQCUgwhMTfAJXcawL7WCwWep5B1FiEXmjAIm4ExC8twDLOPVl8Rxjwt
    C2KK6gK8fpnnoFgWqi2wtTEySS25fitLwSStgbzwKoHofa+FGkOYFNi9l87nsi8XvhvwuVdGhSHSpLcC
    ApXrMOECWDisNigOr3Iye1axwMJBGsFCTqt+THAwuTULeaC60mxrri0YnB7kJbAyngTVQlHFMNHwhC9c
    CorBermC7OseRLZ7Hb2yc1DvQ1PjYuiLPfjQ7tPbif0X+HuQB8PRcQ1sCaKHgghcQSAV7I8GgxbMIhUF
    qi0CYWaPHRZ07PWofgOROMFDyrB7PY1O2TccVF07VmO6bl0MQu1ay7AJ0l4KtKuV7LNnT6ePe0A34Inv
    4N5tALHXUL0uBJAuQX+xwD6VPu3hzIgXmeCWmkOD42bHlekYGUzIVpm21lbeSPQAdJXF7hzEW3LYwYQN
    +3CUQ50O4YN8aifYNc8THrlJukwdyOiKIQwBloeoP17kBstAbA+KQ+E7xN4L6cW2c8EgrTmgnc7HgJD7
    MU/SAaWZJGJsSm85/76E9Caoym+Q4YW6Lgce/rnGwA6objJbM6XRh4Ty6RwCsAJHzSGI4UdYVRG8QheD
    hWUzrnHCTDMOnpwjHNNFN2CnXyJpLPaSEsDWhFuNcTUyZRmgD+LmAuC0KGtzq0MW9JsdfrQGMGwBDA0A
    Cu7CSzx0euP6M+pEHahtGwz0lkGoj2opoRnU1jwcI4OGnFMVlaSbeQkl8GItGAq6c5WnZWbrnSgWWCBJ
    CogL+U0oCkFcJnuBAwmYrUBQcEd8QtzYD8VwMvVH4GQKlkJzvgqpilRTMMluUD8iv6mRcrVX231XqnOf
    bVkPIFvL5hGTlsG4XkNwiXV4T2j5O2KQQy+9CIQShiOx0AG+K5CkNiZQpDTaFCltO/XWSWlNYKRki5Rn
    rclCIefBYBvVEXcIVRKZiTsLFgCCY72PGKB5rRDn3qtW06ZHM32GZTtGpnUF+4tBPRW6Aq/wcFqs9fHA
    Zi9QnuA/j0VmhGpV1s/3EuQH1cWA1DAB2OefTBnF7TSXPKfZssHUpwtslVGRDNOGX/FKP0o2PSHWVrM0
    l4ByPv3HVNOnN0wRqIivxpJ58iJgYbCGKHEpaUZO1/BBIqJ0TmIVWt/CQu83bRTsE48zyI1FgYEwcZIX
    R210NfJq+ydZTJZvi1k1PlSNG5VTcNgCXVxEId/QJKYISE1YJsSYssBDJfa0kHxJk2jNMKJG8T2bPp7C
    UgISYSW+0rC8aNp9Gm+GChxb2/PaaJSGrn33kWQ3mYM9fyFD2n32BfIPnIg6AMGfyDUss1aiBE8uVlwp
    ooWHE9MqNRYQ6mhTI5VY+E2hlFoeL519NaV/+Y0XZxHfRpPjYd1kODj54PThg6NV4wnICY4oip1ACHsE
    mXzuJWIykqo1hTwknK9pXlIwrJgq+QIycg+zFDb96uKZcYm5kgbc+Sr+oD2vHuVuf54z0TGBEjDfy5Ur
    pSO8v7SnwQq5l/uLcIl+OtX01E0/UQFbTggNtFGjagW4LCbKmRJknOkIkkv8naxcBYelU3ZQmdNKiJgJ
    fTSs8/wrB7EcKlt4DRRgvQEmKtU+Rpj3Fw4erIGLwiUqaWDpfHv9R6QHZCZBTxdgrSHLwEquggH28Rzi
    LkQgtC8AFC4FdyGm2GvIitxWq+vNRBrBcDJJchxuE7CrMare1jGmyaQxaT+yyS1S0wEw6viqNbwRgY7Z
    n8g6VC1SVj5RFpCsY9u7MyRLkP3Rxp4qRUR2meDxKuxl0FD7KcR5z9NEb4kUdyoCyS1VxpEdhFv2ZQW5
    qLQwuCeQCR0q01J3JdI8GVnLeZwud8cnTKRGIsEN5XxeRn+mkkcFYzjUtTbpTD52Ls6mztnZlOm0S+ig
    mFVRO3vy5ROzvigE2Xz+FTu/oQoo2JFPn3ysSpuVKkMkn6fLMJCU6x00KovVmxWyX60+NcomJLdqkyOT
    DXzCeSD1T4fpVVbAWCvR0HUsrF00OiAQIBrVaT9WLTxpH8Fo1zeKaOV4AM1q5WqtSrC/B9Cj6ijaGZpY
    /5BKL1W16IUK30Fl1njdQdlbEK001hcFjKHWmUMprxGgvcauGBhSCkgHjuRGFH7GrjnPvAgNFaZNMS/U
    DgBGnIYiM0HFRnDSicyFFkWRibHjRF6Z+IvMC2xRZrihtqxVxs6+k2AxyRmeDAcPjx80RgWpL+w49PMU
    N4bAeWKVQpZaHZWfWLEHW5oADtSCKPUCQT55EV4tLG/phZE3C6OwWFsYG3O6C7A/CsCtfDAbWA8+OA2s
    k9ED35qdPuLWAz8YfTCcByenwUMpuylxu0hLf4FeGB/IZHqztJRW3YfMBRInBJe8cCUvJAtQcuwwW57Y
    wETXMNFF56aLUbuhwqRYQib58PRWqCxPZ5i5PeppE1uUYEJIG1CL0Y/QMST5yYgiEDAhdVcB61qocApB
    QylX+2hnKf6EvFP7iFAoxwTwINYynJmTzmBHEM7nkBmDQHOGiRbWBXleDEaE7ysvT6j+RHbLw1Lp92WN
    VJyL0iosWOIsiN6W5hgX5WrIMes/P3/x1fnZl+eXfbnupwnmutJwVdujAwNZRgca6ZrHE4jCUVYrCylT
    OvgB6TEoAx1Fzuu2y5OOsp5n90j3Ek+aAFztuJXdUocIg0a70AmcNofNUapx0yqO1kBaqUb3wqf+gsee
    CX2DkuJlsKINCy9jb+mF1EobmW4QUnXTk7wh8eeFERul9fWUjfSAptYKQCV42eSqsvx+fWHky/Vjz8RG
    VTUD5DsoIaYIwYNiLQQNGVZ9Qr/EMg5JIMYeISTj6SrR8Fjbo9AE/SmRiMmHDOrAlYHLTnxJzL+hGcwU
    36rZWBrHYNCBa9IxhniIRDNr/+SefXx24aItP8InsOVHjBe+NPsy8EXDUBE0BrCHpwMbvJmNYz89U3EE
    LiNpeQCyKbvHmpEwanrioFy3B0xPsHX4cPDIfvz55Xl92laxSvoPUTuAYMuQbnBRuQTiJbTbWKIKQkGu
    ZqtMhUwyYFokql1ESTOlfJnGqoSb7NGOww9djSIY7Wq1pm3VnqqqVV0ZdxSLkOY6uNs8yRlCNx7oNDPn
    jmGQ/1+DKR9B++hkG7qm/Vt19o05nWkagnbJXcOZ2nQD0LQ2wLaKIVvl+IoNGHZSgoN5INiKUFxLqxBu
    ySQEEtdhJo2DiQQQrlt+JX6J10W8bsCX6hBNzAIDAVkXJbkmGzWlGbC5YJIhGCEKYQaqM9B1mRR2TIUo
    QAA5Yzz0R33DqDA3BGzNTzYH01HqcadPn6g41kFlNlQ9BYFsM8Zmn6PvkuxBkutMQ6bIyYMjFafVluSD
    x6mYggbFrVFmUvVqT8Abylw09JtWMJEbgAi3jVM6l7xQhQbP93km88kUzNOS4+C0vIKApugLOhmKYbuC
    eho4FIXO3JWRMHTdYczUEd1um6VWd3YxNg58DCC6pzm2MrDjW2yZUjQQ8kqRUNx7u+zF8FZ70VUnbmly
    +4BplyK3zpo2FantaObZ2X8++bi/S88bB1O3qvnWOdVvScufvi0V/wWKjWeDXYKCZoLuGugLkVQXATov
    LikhosvDtWvMrXOh229QVGdFDiRp9VsLr96z5J2fvQokhqzouzD5ztvTV39Mn0xYKX+/KZj13gYQUChG
    MfaEXeUeLOnrPj72v2HQjwDzVIVHuHPm1ErG/xSz66YqgyQ/LZFOZPRND9hKT3XmIdqv+6hp/SPWB0ZW
    MyNpBmzC+q/Ggw9Hm74tI9UDQqX7D1m1HKMs6mhUzhkGP/Xd/k8GYQe8OSrcotIu8Zr6wWHXcLA2VDzC
    v5BMU9Lt/6RnNsP7dBFUjegEqJGo6KE2AqwbGmKSPnlD+XLNpXQMcbLrK9vETTrmUWH0ztvsCkzVVfRN
    gNqFGldP+OpVi8sboGblgTNCpQOCqEYg3AYJlahAIO9fV0YNQmlB9yqBo5Qgt7kfpSvkDoqTFBVcfX1N
    58//4/L8Asfjhbx277Pz6fTs7+fT80twFASUQIpZQYHqZ6hrJSTAf788P3+u2slYw1LNLmk6NnokUkgg
    Ri5MV2VUEUN13Ns63vpRRXoHFUjrMKg2HRax19XtGyyRxVkBVI8GppEi0CXG48eDN9xQWdLByqp6wUV0
    wUm0tRXWwCWGoDYzbYjhadcmbzYG+q4NuHUL3s0mdPDzZ3BUFGnm1le9i6Hy9pidl0lTeSsCVXWc6t5g
    0vM0UoB4GV0FBFOYrv9bFWY8JLDpnbJKPCKeXOF54vD0DUV3m9FKJt89w9Vd3X9NvuMbPPhul3whcBez
    6S0WL8ObZE1uA3zDndaIvgEe/Wg0bt96O38qhBgzSrJZ0yG+k+mUNEJEF4UziBruHTx5euk+fuFefvH8
    EKOHhSeJ8VNbpN3DdCxYeX5ARNEHvu5J79xRXNCGUiwtkwgvEJodxpB0m//sR4gLecb63zbm7u+Sk9ey
    cFJOAIounBSpixc/6S73DoFBONuECZ2upKFZ+OaMJhCPp1y6UwOO8hNPvmqFXarNkK6JeMOl/awgBhgB
    eRxh1YynIsttigPbEZlbuHdqjnoHE4zTt5fytVX3Ik8h1o/dwRAERl4ZeXnv5YF7/vzlIcvmE3q4+OTl
    YbXLWUTWbcfoeziWht7DgYdvKh0QVtfOJmTx4FaWRGHyuvzAV9nGiInneqf1oS6WMAN9pVwec2LT9yV3
    eOInoYN0ibQiTb2l2JMGBM8jYOcpa6OsVl+7gUQspzPS1YIn8ma+PhHH+9U6h1VoGmdXCAwI/Wt1duWo
    w/Wcz3V6SEwWIfy0F0Uc7Usy1DLkw5iUu7rvLzM9rdp7PBGevrHhdiuU23RPY/v94d6b6wm9X3W7pmBG
    uENRsEzx6+jJoKUnlw09+Qyenl/S0/Tx9OmTu/Rm0NCby0pvPiM89ySWN1YiZfm8skjlct6yHuHrC2P2
    7ZnGD6sa2u/fa6hZwCNe8LcgKDph68ml/F9EdjCvCu0aTkdl7jDZ7yzie11bvb0h734j/jVZLRUBC3Lv
    bTrebXrtMqKO4DHSeFuFxG0EtetR+soMTmbQNa+6uPrazlvBTXeI6rfbtrC+ldqnKW2Cp7qlxNmM+H6N
    ymatNqmPsRV01dIh11XnYbPAWSHpNw5U+j/VOoEjjd6+Pr2qwVB5rvZcX1toKqj0MiQKp2qs1URx5T/1
    bTpQUAyV1xP0gScNuNXJyXMCk3nKd6rGFJdB2FUJGRbXKNxq0KKmtr8btf2kXkHNGEgEY0aKVI8sMZvd
    p3WXmZFLFDc9ht0yJ73r1b5E3rBh7bd2TPGq66J70/q1un9WaazrRv/bK7yxLXNf76tOYzprgc1jumbu
    2Kir10YE6SrB22DuzBPXvNjmVO39olbmR7bHNcdeon7fGmRWVVZfR2Tv9poKGV6MoBitkrO5uuraJZxk
    VkHgrvn6SL0TkXTTbodYyz841AVzhvhgGBLI9uA3Df9R3abfbPTLjThD5a8aUdxrVZOaZwY7TjN+S85f
    X/5UL0U0EVd3xA3OtpeqV/qr01u9wuqlwiZUcyUGsq37lro5c4tINA+yb9MOa+etl65RVb9Zeh+vxfQP
    d+CT12E6UWGXwTI6qWGon/rLrEU7mYoDq/Z+d1xDrsDbt3Rx6I6opXZE04rtXtM7Vfna67oxb9ZZDdva
    1V9O0duON9GW/BFu/irhpimb/P+PNs8vu+NMaH+zCJNc288IMOVFnHcRX9Yo+bXCy91T/hFd/k6iy9eQ
    199lcClvlwADdeHSfBnMla9b36q9EqTJDvPeZmfdT9/nueuSxsMdlzT+iIb/iIZ/p9EwxZjvpM6qP08z
    PB0MjHxrpdK80i0G9fHg8O7A+A67WYH/Ejtj4vzXjSbeNMy/azV3RPm9V4wC0yoM8sPZWw5/9A0F/X2j
    reiHvpwC86oPtsGv7hCIfX1DbudGuxv0mDd2O5CVxdhvfl7AtE3kdtgkvxeoXx0YM/PmofyqcDPS+PRs
    WDmJ+ssaYzaoeuq3v7c7qq8E7bM/oqRmHFp9naI9xHywaKMEXn5sG9WSeWWxSPPwBx7gF4wFiXSPPgTL
    HPQkji3EwmlDqY+ekwsyzlR9mvUxvtyJwUujU36INVsFk3sHlD7jVyWYZcmDYUirYeH2Fa++Y9b1ZTOA
    p1f1QFZ/ZN7qGnK7DOKkgt2D/O6wtxMv3mMweImsl/17r4CYzcs+8aJMqg8I6reGax8RlAuTX3nX3bSe
    jhmhpSzCyMbPSeSu74HVvA0MP0fnQk8HjBUBDbPySt6wsOX7qPqrfM2PH8rPqsmPSJDm4duCfnytvWY2
    2UOPaPnR0BqMq5/WMrZQLv9qmoZV71D37rGX+tvV6nWQDSbdzZfJap+u9kF+zGtr+uNza0iy0D8lqCMW
    fWBZ3SVpg4f4BiGIJn4SDqgnU6KXOKavRbrqQ7gw8KV65RNNE374Qd4iow9yTkCC6i34Msme+ajc3/E2
    FILoBnlnarOnUMoPZ0os5iOa0BulINzYSD9kG8kWQcIm1eVVUYc7od7UczFcDrmYnMhm+SU8N8JFT45Z
    hkGsq7z95NFgIKFyju9SNNpfqi/Z6VcATTgwOcZPj2vQIV2V3lefa7qAKCz2rumz+sqsS6u/4Or/WUAf
    j79jU+Qn4/GtKHx71J+PFyDqxQxmGDe7OogbDsQWdnAjCf6dNDG3p9otWa2vGe4SrF1ySJ8Ik9/3bpqC
    1rdEUeXi2JOvfYEjou+i5SlMGdNnPGKWshI//ob/8wgv03kSA4MXUvdVGAwObaf3v2k9Q9SiYgAA
  path: /run/scripts/setup_sap.sh
  owner: root:root
  permissions: "0755"
  append: false

runcmd:
  - [bash, "/run/scripts/setup_sap.sh"]
